### ISSUE TITLE
Nullpointer Exception when calling BeerInventoryServiceFeignClientImpl.getOnHandInventory

### ISSUE THREAD

**Issue by artshishkin** [artshishkin/art-sfg-mssc-brewery#68]
```
<#85ea4577> j.l.NullPointerException: response == null
	at b.http.HttpHandler.handleFinish(HttpHandler.java:66)
	at b.h.HttpClientHandler.handleReceive(HttpClientHandler.java:258)
	at o.s.c.s.b.b.BraveHttpClientHandler.handleReceive(BraveHttpClientHandler.java:57)
	at o.s.c.s.i.w.c.f.TracingFeignClient.handleSendAndReceive(TracingFeignClient.java:103)
	at o.s.c.s.i.w.c.f.TraceFeignBlockingLoadBalancerClient.execute(TraceFeignBlockingLoadBalancerClient.java:99)
	at f.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119)
	at f.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at f.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at c.s.proxy.$Proxy224.getOnHandInventory(Unknown Source)
	at n.s.s.b.s.i.BeerInventoryServiceFeignClientImpl.getOnHandInventory(BeerInventoryServiceFeignClientImpl.java:27)
	at n.s.s.b.s.b.BrewingService.lambda$checkForLowInventory$0(BrewingService.java:32)
	at j.u.s.ReferencePipeline$11$1.accept(Unknown Source)
	at j.u.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at j.u.s.AbstractPipeline.copyInto(Unknown Source)
	at j.u.s.ForEachOps$ForEachTask.compute(Unknown Source)
	at j.u.c.CountedCompleter.exec(Unknown Source)
	at j.u.c.ForkJoinTask.doExec(Unknown Source)
	at j.u.c.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at j.u.c.ForkJoinPool.scan(Unknown Source)
	at j.u.c.ForkJoinPool.runWorker(Unknown Source)
	at j.u.c.ForkJoinWorkerThread.run(Unknown Source)
Wrapped by: <#a0126a60> j.l.NullPointerException: null
	at j.i.r.NativeConstructorAccessorImpl.newInstance0(Unknown Source)
	at j.i.r.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at j.i.r.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at j.l.r.Constructor.newInstance(Unknown Source)
	at j.u.c.ForkJoinTask.getThrowableException(Unknown Source)
	at j.u.c.ForkJoinTask.reportException(Unknown Source)
	at j.u.c.ForkJoinTask.invoke(Unknown Source)
	at j.u.s.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
	at j.u.s...
```

**Comment by artshishkin** [comment]
```json
{
  "_index": "filebeat-7.10.1-2021.02.16-000001",
  "_type": "_doc",
  "_id": "oUpBq3cBRTigmxl0YVIo",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2021-02-16T14:32:03.077Z",
    "log": {
      "offset": 48652,
      "file": {
        "path": "/var/lib/docker/containers/4a23ea7ed35c99a382fe0e56d805f214b6eba21deba81eeee4a46f7940a713b1/4a23ea7ed35c99a382fe0e56d805f214b6eba21deba81eeee4a46f7940a713b1-json.log"
      }
    },
    "ecs": {
      "version": "1.6.0"
    },
    "message": "Unexpected error occurred in scheduled task",
    "level": "ERROR",
    "springAppName": "beer-service",
    "agent": {
      "name": "a5ea92389855",
      "type": "filebeat",
      "version": "7.10.1",
      "hostname": "a5ea92389855",
      "ephemeral_id": "cc95a6bd-3079-4933-9849-772e5e2c9267",
      "id": "e49d8237-53bf-45e2-ae57-3005f6578316"
    },
    "stream": "stdout",
    "stack_trace": "<#85ea4577> j.l.NullPointerException: response == null\n\tat b.http.HttpHandler.handleFinish(HttpHandler.java:66)\n\tat b.h.HttpClientHandler.handleReceive(HttpClientHandler.java:258)\n\tat o.s.c.s.b.b.BraveHttpClientHandler.handleReceive(BraveHttpClientHandler.java:57)\n\tat o.s.c.s.i.w.c.f.TracingFeignClient.handleSendAndReceive(TracingFeignClient.java:103)\n\tat o.s.c.s.i.w.c.f.TraceFeignBlockingLoadBalancerClient.execute(TraceFeignBlockingLoadBalancerClient.java:99)\n\tat f.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119)\n\tat f.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)\n\tat f.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)\n\tat c.s.proxy.$Proxy224.getOnHandInventory(Unknown Source)\n\tat n.s.s.b.s.i.BeerInventoryServiceFeignClientImpl.getOnHandInventory(BeerInventoryServiceFeignClientImpl.java:27)\n\tat n.s.s.b.s.b.BrewingService.lambda$checkForLowInventory$0(BrewingService.java:32)\n\tat j.u.s.ReferencePipeline$11$1.accept(Unknown Source)\n\tat j.u.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)\n\tat j.u.s.AbstractPipeline.copyInto(Unknown Source)\n\tat j.u.s.ForEachOps$ForEachTask.compute(Unknown Source)\n\tat j.u.c.CountedCompleter.exec(Unknown Source)\n\tat j.u.c.ForkJoinTask.doExec(Unknown Source)\n\tat j.u.c.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)\n\tat j.u.c.ForkJoinPool.scan(Unknown Source)\n\tat j.u.c.ForkJoinPool.runWorker(Unknown Source)\n\tat j.u.c.ForkJoinWorkerThread.run(Unknown Source)\nWrapped by: <#a0126a60> j.l.NullPointerException: null\n\tat j.i.r.NativeConstructorAccessorImpl.newInstance0(Unknown Source)\n\tat j.i.r.NativeConstructorAccessorImpl.newInstance(Unknown Source)\n\tat j.i.r.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)\n\tat j.l.r.Constructor.newInstance(Unknown Source)\n\tat j.u.c.ForkJoinTask.getThrowableException(Unknown Source)\n\tat j.u.c.ForkJoinTask.reportException(Unknown Source)\n\tat j.u.c.ForkJoinTask.invoke(Unknown Source)\n\tat j.u.s.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)\n\tat j.u.s...\n",
    "@version": "1",
    "thread_name": "scheduling-1",
    "host": {
      "name": "a5ea92389855"
    },
    "input": {
      "type": "container"
    },
    "container": {
      "id": "4a23ea7ed35c99a382fe0e56d805f214b6eba21deba81eeee4a46f7940a713b1",
      "name": "brewery_beer-service.1.ybnsq8b9ch6rt4y0cnmy02wfx",
      "image": {
        "name": "artarkatesoft/beer-service:latest@sha256:90d593a25b795aac08f9a81c2673bad3db31dc6f3876c5a5f8988d67608dee06"
      }
    },
    "docker": {
      "container": {
        "labels": {
          "com_docker_swarm_task_name": "brewery_beer-service.1.ybnsq8b9ch6rt4y0cnmy02wfx",
          "PROJECT_NAME": "beer-service",
          "com_docker_stack_namespace": "brewery",
          "com_docker_swarm_task_id": "ybnsq8b9ch6rt4y0cnmy02wfx",
          "com_docker_swarm_service_id": "lla3wd4mwo48oauv4mxqrsbdy",
          "com_docker_swarm_task": "",
          "PROJECT": "net.shyshkin.study:beer-service:jar:0.0.7",
          "collect_logs_with_filebeat": "true",
          "com_docker_swarm_service_name": "brewery_beer-service",
          "decode_log_event_to_json_object": "true",
          "com_docker_swarm_node_id": "72ir0q5akbrkppvh1hi914tlf"
        }
      }
    },
    "logger_name": "org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler"
  },
  "fields": {
    "@timestamp": [
      "2021-02-16T14:32:03.077Z"
    ],
    "suricata.eve.timestamp": [
      "2021-02-16T14:32:03.077Z"
    ]
  },
  "highlight": {
    "level": [
      "@kibana-highlighted-field@ERROR@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1613485923077
  ]
}
```
